server:
  host: localhost
  port: 8085

database:
  host: localhost
  port: 3306
  username: portal
  password: 4f242f2491e53c8e72f14c373f3dd19d
  dbname: PORTAL
  maxIdleConns: 10
  maxOpenConns: 1000
  connMaxLifetime: 1h

redis:
  host: localhost
  port: 6379
  password:
  database: 0
  ttls:
    common: 2h

client:
  debug: true
  timeout: 1m

i18n:
  languages: en

cors:
  allowOrigins: '*'
  allowMethods: GET,POST,PUT,PATCH,DELETE,HEAD
  allowHeaders: Origin,Content-Length,Content-Type,Authorization
  exposeHeaders: Content-Length
  allowCredentials: true
  maxAge: 24h

log:
  level: debug
  consoleLoggingEnabled: true
  encodeLogsAsJson: true
  fileLoggingEnabled: true
  directory: './'
  filename: 'log.log'
  maxSize: 1
  maxBackups: 1
  maxAge: 1